num_worker: 0
work_dir: ./work_dir/hmbdb51/bone_CoM_0/

# feeder
feeder: feeders.feeder_hmdb51.Feeder
train_feeder_args:
  data_path: ./data/hmdb51_2d_processed.pkl
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  bone: True

test_feeder_args:
  data_path: ./data/hmdb51_2d_processed.pkl
  split: test
  window_size: 64
  p_interval: [0.95]
  bone: True
  debug: False

# model
model: model.HDGCN.Model
model_args:
  num_class: 51
  num_point: 17
  num_person: 1
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 0

#optim
weight_decay: 0.0004
base_lr: 0.1
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 90
nesterov: True
